const points = document.querySelector("#typing-points")
const highscore = document.querySelector("#typing-highscore")
const time = document.querySelector("#typing-time")
const screenTxt = document.querySelector("#typing-text")
const screen = document.querySelector("#typing-screen")
